"""delete column price from portfolio

Revision ID: 5b96ee0f3d6e
Revises: 4d1c9a776a0d
Create Date: 2026-02-25 11:31:19.142755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b96ee0f3d6e'
down_revision: Union[str, Sequence[str], None] = '4d1c9a776a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
