"""add portfolio model and schema

Revision ID: 7dfd8169c3b7
Revises: 1d25da0b7712
Create Date: 2026-02-16 16:39:26.993630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfd8169c3b7'
down_revision: Union[str, Sequence[str], None] = '1d25da0b7712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_description'), 'portfolio', ['description'], unique=False)
    op.create_index(op.f('ix_portfolio_name'), 'portfolio', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_name'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_description'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
