"""add tickets and portfolio models/schemas

Revision ID: b8b8ba081cb7
Revises: 7dfd8169c3b7
Create Date: 2026-02-16 17:04:36.732694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b8ba081cb7'
down_revision: Union[str, Sequence[str], None] = '7dfd8169c3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_description'), 'tickets', ['description'], unique=False)
    op.create_index(op.f('ix_tickets_name'), 'tickets', ['name'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_description'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
